---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
adidas-database-service:
  ribbon: 
    listOfServers: http://localhost:8010
adidas-event-service:
  ribbon: 
    listOfServers: http://localhost:8010
adidas-email-service:
  ribbon: 
    listOfServers: http://localhost:8010
server: 
  port: 8096

spring:
  application:
    name: adidas-subscription-service
 
feign:
  client:
    config:
      adidas-event-service:
#        connectTimeout: 5000
#        readTimeout: 5000
        loggerLevel: full
      adidas-database-service:
      #  connectTimeout: 5000
       # readTimeout: 5000
        loggerLevel: full
  hystrix:
    enabled: true

# To set thread isolation to SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

date:
  format: yyyy-MM-dd
               
logging: 
  level: 
    com: DEBUG  