---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
server: 
  port: 8092

spring:
  application:
    name: adidas-event-service
ribbon:
    eureka:
        enabled: true 
logging: 
  level: 
    org: 
      springframework: 
        web: DEBUG